apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console
  namespace: platform
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
spec:
  ingressClassName: nginx            # 你的 Ingress-NGINX class
  rules:
  - host: minio.local                # 需要在本机 hosts 解析到 worker
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: minio
            port: { number: 9001 }   # 指向 console 端口

