apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-cpemon-api
  namespace: cpemon
spec:
  # 至少保留 1 个副本
  minAvailable: 1
  selector:
    matchLabels:
      app: cpemon-api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-acs-ingest
  namespace: cpemon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: acs-ingest
