apiVersion: v1
kind: Secret
metadata:
  name: minio-aws
  namespace: cpemon
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${MINIO_ACCESS}
  AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET}
  AWS_ENDPOINT_URL: ${ENDPOINT}   # 例如 http://minio.platform.svc.cluster.local:9000
  AWS_DEFAULT_REGION: us-east-1   # MinIO 不强制区域；给个默认值即可
  S3_BUCKET: ${BUCKET}

