apiVersion: v1
kind: Secret
metadata:
  name: minio-conn         # Secret 名，CronJob 会引用它
  namespace: cpemon
  labels:
    app: db-backup         # 便于筛选/清理
    cpemon/component: storage
type: Opaque
stringData:                 # stringData：明文输入，apiserver 负责转成 data(base64)
  endpoint: ${ENDPOINT}     # 例：http://minio.platform.svc.cluster.local:9000
  bucket: ${BUCKET}         # 例：mysql-backup
  accessKey: ${MINIO_ACCESS}
  secretKey: ${MINIO_SECRET}
