apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: acs-ingest-pdb
  namespace: cpemon
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/part-of: cpemon
      app.kubernetes.io/name: acs-ingest
