apiVersion: v1
kind: Namespace
metadata: { name: cpemon }
---
apiVersion: v1
kind: Namespace
metadata: { name: platform }
---
apiVersion: v1
kind: Namespace
metadata: { name: backup }
---
apiVersion: v1
kind: Namespace
metadata: { name: ingress-nginx }
