apiVersion: v1
kind: Namespace
metadata:
  name: cpemon
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: cpemon
---
apiVersion: v1
kind: Namespace
metadata:
  name: platform
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: backup
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: backup
---
apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: cpemon-mvp
    app.kubernetes.io/name: ingress-nginx
