name: CPE Heartbeat Simulator - Build & Push

on:
  push:
    tags:
      - "cpe-sim-v*.*.*"   # 例如 cpe-sim-v0.1.0
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      ECR_REPOSITORY: cpe-heartbeat-sim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1) 通过 OIDC + STS 获取临时凭证
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/cpemon-ci-github-role
          aws-region: ${{ env.AWS_REGION }}

      # 2) 调试当前身份
      - name: Debug STS caller identity
        run: aws sts get-caller-identity

      # 3) 登录 ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 4) 构建并推送模拟器镜像
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: ./scripts
          file: ./vm3/cpe-sim/Dockerfile
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.ref_name }}

